server {
  listen 80;

  server_name localhost;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  # 若你有 API 代理，也可以配置：
  # location /api/ {
  #     proxy_pass http://your-backend-api:7050;
  #     proxy_set_header Host $host;
  # }
}
